<?php

/**
 * Implements hook_libraries_info().
 */
function roomify_periodic_pricing_libraries_info() {
  $libraries['fullcalendar-scheduler'] = array(
    'name' => 'Fullcalendar Scheduler',
    'vendor url' => 'http://fullcalendar.io',
    'download url' => 'https://github.com/fullcalendar/fullcalendar-scheduler/releases/download/v1.2.1/fullcalendar-scheduler-1.2.1.zip',
    'version arguments' => array(
      'file' => 'scheduler.min.js',
      // 1.2.1
      'pattern' => '/(\d+\.\d+\.\d)/',
    ),
    'files' => array(
      'js' => array(
        'scheduler.min.js',
      ),
    ),
    'variants' => array(
      'minified' => array(
        'files' => array(
          'js' => array(
            'scheduler.min.js',
          ),
          'css' => array(
            'scheduler.min.css',
          ),
        ),
        'dependencies' => array('fullcalendar (>=2.6.1)'),
      ),
      'source' => array(
        'files' => array(
          'js' => array(
            'scheduler.js',
          ),
          'css' => array(
            'scheduler.css',
          ),
        ),
        'dependencies' => array('fullcalendar (>=2.6.1)'),
      ),
    ),
  );

  return $libraries;
}

/**
 * Checks if the FullCalendar Scheduler Library is loaded.
 *
 * @return bool
 *   A boolean indicating the FullCalendar Scheduler status.
 */
function roomify_periodic_pricing_fullcalendar_scheduler_loaded() {
  if (rooms_library_loaded('fullcalendar-scheduler', 'minified')) {
    return TRUE;
  }
  else {
    // Alert the authorized user/administrator to the abscence of the library.
    drupal_set_message(t('The FullCalendar Scheduler Library could not be found.
                          Please check the installation instructions and the <a href="@status">Status Report</a>.',
      array('@status' => url('admin/reports/status'))), 'warning');
    return FALSE;
  }
}

/**
 * Implements hook_menu_alter().
 */
function roomify_periodic_pricing_menu_alter(&$items) {
  $items['admin/rooms/units/unit/%rooms_unit/pricing']['page callback'] = 'roomify_periodic_pricing_page';

  $items['admin/rooms/units/bulk_pricing_management']['page callback'] = 'roomify_periodic_pricing_bulk_pricing_management';
}

/**
 * Implements hook_menu().
 */
function roomify_periodic_pricing_menu() {
  $items = array();

  $items['rooms/units/unit/%rooms_unit/roomify-pricing/json'] = array(
    'title' => 'Pricing Info',
    'page callback' => 'roomify_periodic_pricing_json',
    'page arguments' => array(3),
    'access callback' => 'rooms_unit_access',
    'access arguments' => array('update pricing', 3),
    'type' => MENU_CALLBACK,
    'weight' => '30',
  );

  $items['admin/rooms/units/unit/%rooms_unit/roomify-pricing'] = array(
    'title' => 'Pricing Management',
    'page callback' => 'roomify_periodic_pricing_manager_page',
    'page arguments' => array(4),
    'access callback' => 'rooms_unit_access',
    'access arguments' => array('update pricing', 4),
    'type' => MENU_CALLBACK,
    'weight' => 30,
  );

  return $items;
}

/**
 * The PricingManager page shows when selecting a date range in the
 * pricing calendar - will allow a user to change price/discount.
 */
function roomify_periodic_pricing_manager_page($unit, $event_id = NULL, $sd = 0, $ed = 0) {
  // Include modal library.
  ctools_include('modal');

  $form_state = array(
   'title' => t('Pricing Management'),
    'ajax' => TRUE,
    'build_info' => array(
      'args' => array($unit, $event_id, $sd, $ed),
    ),
  );

  $output = ctools_modal_form_wrapper('roomify_periodic_pricing_manager_form', $form_state);

  if ($form_state['executed']) {
    $output = array(ctools_modal_command_dismiss());
  }

  print ajax_render($output);
  exit();
}

/**
 * Form to manage the room units pricing/discount.
 */
function roomify_periodic_pricing_manager_form($form, &$form_state, $unit, $event_id, $sd, $ed) {
  $date_format = variable_get('rooms_date_format', 'Y-m-d');

  $start_date = new DateTime($sd);
  $end_date = new DateTime($ed);

  $form['unit_id'] = array(
    '#type' => 'hidden',
    '#value' => $unit->unit_id,
  );

  $form['event_id'] = array(
    '#type' => 'hidden',
    '#value' => $event_id,
  );

  $form['start_date'] = array(
    '#type' => 'hidden',
    '#value' => $start_date,
  );

  $form['end_date'] = array(
    '#type' => 'hidden',
    '#value' => $end_date,
  );


  $form['event_details'] = array(
    '#prefix' => '<div class="event-details">',
    '#markup' => '<h3>' . t('Date range selected: @startdate to @enddate', array('@startdate' => $start_date->format($date_format), '@enddate' => $end_date->format($date_format))) . '</h3>',
    '#suffix' => '</div>',
  );

  $form['op'] = array(
    '#type' => 'fieldset',
  );

  if ($event_id == 'daily') {
    $price_options = rooms_price_options_options();
    unset($price_options[ROOMS_ADD_DAILY]);
    unset($price_options[ROOMS_SUB_DAILY]);
    $form['op']['operation'] = array(
      '#type' => 'select',
      '#title' => t('Operation'),
      '#options' => $price_options,
      '#default_value' => 'replace',
    );

    $form['op']['amount'] = array(
      '#type' => 'textfield',
      '#title' => t('Amount'),
      '#default_value' => '',
      '#size' => '5',
      '#description' => t('Amount to apply for rule'),
      '#maxlength' => 10,
      '#required' => TRUE,
    );
  }
  elseif ($event_id == 'weekly') {
    $form['op']['amount'] = array(
      '#type' => 'textfield',
      '#title' => t('Weekly Rate'),
      '#required' => TRUE,
    );
  }
  elseif ($event_id == 'monthly') {
    $form['op']['amount'] = array(
      '#type' => 'textfield',
      '#title' => t('Monthly Rate'),
      '#required' => TRUE,
    );
  }

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
  );

  return $form;
}

/**
 * Submit callback for roomify_periodic_pricing_manager_form form.
 */
function roomify_periodic_pricing_manager_form_submit($form, &$form_state) {
  $event_id = $form_state['values']['event_id'];

  $unit_id = $form_state['values']['unit_id'];
  $amount = $form_state['values']['amount'];
  $start_date = $form_state['values']['start_date'];
  $end_date = $form_state['values']['end_date'];

  if ($event_id == 'daily') {
    $operation = $form_state['values']['operation'];

    rooms_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, $operation);
  }
  elseif ($event_id == 'weekly' || $event_id == 'monthly') {
    roomify_periodic_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, $event_id);
  }
}

/**
 * Update weekly and monthly calendars.
 */
function roomify_periodic_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, $type, $days = array()) {
  if ($type == 'weekly') {
    if (!empty($days)) {
      $rc = new UnitWeeklyPricingCalendar($unit_id);
      $events = $rc->calculatePricingEvents($unit_id, $amount, $start_date, $end_date, ROOMS_REPLACE, $days);

      $rc->updateCalendar($events);
    }
    else {
      $rc = new UnitWeeklyPricingCalendar($unit_id);
      $pe = new PricingEvent($unit_id, $amount, $start_date, $end_date, ROOMS_REPLACE);
      $events = array($pe);

      $rc->updateCalendar($events);
    }
  }
  elseif ($type == 'monthly') {
    if (!empty($days)) {
      $rc = new UnitMonthlyPricingCalendar($unit_id);
      $events = $rc->calculatePricingEvents($unit_id, $amount, $start_date, $end_date, ROOMS_REPLACE, $days);

      $rc->updateCalendar($events);
    }
    else {
      $rc = new UnitMonthlyPricingCalendar($unit_id);
      $pe = new PricingEvent($unit_id, $amount, $start_date, $end_date, ROOMS_REPLACE);
      $events = array($pe);

      $rc->updateCalendar($events);
    }
  }
}

/**
 * Callback for rooms/units/unit/%rooms_unit/roomify-pricing/json.
 *
 * Return json for daily, weekly and monthly pricing events.
 */
function roomify_periodic_pricing_json($unit) {
  $json_events = array();

  $start_date = new DateTime($_GET['start']);
  $end_date = new DateTime($_GET['end']);

  $json_events  = array();

  // Daily events
  $rc = new UnitPricingCalendar($unit->unit_id);
  $events = $rc->getEvents($start_date, $end_date);
  foreach ($events as $event) {
    $json_events[] = array(
      'resourceId' => 'daily',
      'rendering' => 'background',
    ) + $event->formatJson();
  }

  // Weekly events
  $rc = new UnitWeeklyPricingCalendar($unit->unit_id);
  $events = $rc->getEvents($start_date, $end_date);
  foreach ($events as $event) {
    $json_events[] = array(
      'resourceId' => 'weekly',
      'rendering' => 'background',
    ) + $event->formatJson();
  }

  // Monthly events
  $rc = new UnitMonthlyPricingCalendar($unit->unit_id);
  $events = $rc->getEvents($start_date, $end_date);
  foreach ($events as $event) {
    $json_events[] = array(
      'resourceId' => 'monthly',
      'rendering' => 'background',
    ) + $event->formatJson();
  }

  echo drupal_json_encode($json_events);
}

/**
 * Callback for admin/rooms/units/unit/%rooms_unit/pricing.
 *
 * Builds pricing page by adding calendar and pulling events from pricing table.
 */
function roomify_periodic_pricing_page(RoomsUnit $rooms_unit, $year = '', $month = '') {
  // Set the page title.
  drupal_set_title(t('Edit @unit_name Pricing', array('@unit_name' => $rooms_unit->name)));

  // Add styles.
  rooms_availability_modal_style();

  // Get the current page's URL, striped of the year and month args.
  // This allows us to place this page anywhere, including at
  // unit/%/availability  or  admin/rooms/units/unit/%/availability
  list($url) = explode('/' . $year . '/' . $month, current_path());

  return array(
    '#theme' => 'rooms_one_month_calendar',
    '#top_form' => drupal_get_form('roomify_periodic_pricing_update_form', $rooms_unit->unit_id),
    '#bottom_form' => drupal_get_form('roomify_periodic_pricing_test_form', $rooms_unit->unit_id),
    '#attached' => array(
      'js' => array(
        drupal_get_path('module', 'roomify_periodic_pricing') . '/js/roomify_periodic_pricing.js',
        array(
          'data' => array('roomsPeriodicPricing' => array('roomID' => $rooms_unit->unit_id, 'roomName' => $rooms_unit->name)),
          'type' => 'setting',
        ),
      ),
    ),
  );
}

/**
 * Implements hook_theme().
 */
function roomify_periodic_pricing_theme() {
  return array(
    'rooms_one_month_calendar' => array(
      'template' => 'rooms_one_month_calendar',
      'variables' => array(
        'url' => NULL,
        'top_form' => NULL,
        'bottom_form' => NULL,
        'year' => NULL,
        'month' => NULL,
        'event_type' => NULL,
        'link_options' => NULL,
      ),
    ),
  );
}

/**
 * Default implementation of hook_preprocess_rooms_one_month_calendar().
 *
 * Here we setup the one-month calendar based on a specified year,
 * month, and url.
 */
function roomify_periodic_pricing_preprocess_rooms_one_month_calendar(&$vars) {
  // Load FullCalendar Scheduler.
  rooms_library_loaded('fullcalendar-scheduler', 'minified');

  // Add css styles for one-month-calendar.
  drupal_add_css(drupal_get_path('module', 'rooms_availability') . '/css/fullcalendar.theme.css');

  // If dates are not provided then use the current date.
  $year = (empty($vars['year'])) ? date('Y', time()) : check_plain($vars['year']);
  $month = (empty($vars['month'])) ? date('n', time()) : check_plain($vars['month']);

  // Inject settings in javascript that will be used to setup the three months
  // display.
  drupal_add_js(array('roomsCalendar' => array('currentMonth' => intval($month))), 'setting');
  drupal_add_js(array('roomsCalendar' => array('currentYear' => intval($year))), 'setting');
}

/**
 * Implements hook_rooms_price_modifier_alter().
 */
function roomify_periodic_pricing_rooms_price_modifier_alter(&$price_modifiers, $booking_info) {
  if (!isset($price_modifiers['roomify_periodic_pricing'])) {
    $unit = $booking_info['unit'];
    $end_date = $booking_info['end_date'];
    $start_date = $booking_info['start_date'];

    $booking_parameters = reset($booking_info['booking_parameters']);
    if (is_array($booking_parameters)) {
      $persons = (isset($booking_parameters['adults'])) ? $booking_parameters['adults'] : 0;
      $children = (isset($booking_parameters['children'])) ? $booking_parameters['children'] : 0;
      $children_ages = (isset($booking_parameters['childrens_age'])) ? $booking_parameters['childrens_age'] : array();
    }
    else {
      $booking_parameters = $booking_info['booking_parameters'];
      $persons = (isset($booking_parameters['group_size'])) ? $booking_parameters['group_size'] : 0;
      $children = (isset($booking_parameters['group_size_children'])) ? $booking_parameters['group_size_children'] : 0;
      $children_ages = (isset($booking_parameters['childrens_age'])) ? $booking_parameters['childrens_age'] : array();
    }

    $weeks_months_days = roomify_periodic_pricing_calculate_weeks_months_days($start_date, $end_date);

    $temp_end_date = clone($end_date);
    $temp_end_date->sub(new DateInterval('P1D'));

    $price = 0;

    // If "Monthly rate" is set and the current period is greater than or equal to 28 days.
    if ($weeks_months_days['months'] > 0 && $unit->monthly_discount > 0) {
      $rc = new UnitMonthlyPricingCalendar($unit->unit_id);

      $price = round($rc->calculatePrice($start_date, $temp_end_date, $persons, $children, $children_ages) / 28, 2);
    }
    // If "Weekly rate" is set and the current period is greater than or equal to 7 days.
    elseif ($weeks_months_days['total_weeks'] > 0 && $unit->weekly_discount > 0) {
      $rc = new UnitWeeklyPricingCalendar($unit->unit_id);

      $price = round($rc->calculatePrice($start_date, $temp_end_date, $persons, $children, $children_ages) / 7, 2);
    }

    if ($price > 0) {
      $roomify_periodic_price_modifier = array(
        'roomify_periodic_pricing' => array(
          '#type' => ROOMS_DYNAMIC_MODIFIER,
          '#quantity' => 1,
          '#op_type' => ROOMS_REPLACE,
          '#amount' => $price,
        ),
      );

      $price_modifiers = $roomify_periodic_price_modifier + $price_modifiers;
    }
  }
}

/**
 * Calculate number of days, weeks and months in a given period.
 *
 * @param DateTime $start_date
 * The starting date
 *
 * @param DateTime $end_date
 * The end date of our range
 *
 * @return array
 */
function roomify_periodic_pricing_calculate_weeks_months_days($start_date, $end_date) {
  $days = $end_date->diff($start_date)->days;

  $weeks = floor($days / 7);
  $months = floor($weeks / 4);

  $more_weeks = $weeks % 4;
  $more_days = $days % 7;

  return array(
    'total_days' => $days,
    'total_weeks' => $weeks,
    'more_days' => $more_days,
    'more_weeks' => $more_weeks,
    'months' => $months,
  );
}

/**
 * Pricing update form.
 */
function roomify_periodic_pricing_update_form($form, &$form_state, $unit_id) {
  $form['#attached']['css'][] = drupal_get_path('module', 'roomify_periodic_pricing') . '/css/roomify_periodic_pricing.css';

  $form['unit_id'] = array(
    '#type' => 'hidden',
    '#value' => $unit_id,
  );

  $form['description'] = array(
    '#markup' => '<div>Pricing Rates can be changed from day to day to allow you to fine-tune your prices.</div><br><div>You always enter the full rate amount for the rate you are editing.<br>For example, if your weekly rate is $800 /week you will enter $800 for each night that rate applies.</div><br>',
  );

  $form['rate_type'] = array(
    '#type' => 'select',
    '#title' => t('Rate type'),
    '#options' => array('nightly' => 'Nightly', 'weekly' => 'Weekly (7 nights)', 'monthly' => 'Monthly (28 nights)'),
    '#field_prefix' => t('Set') . '&nbsp;',
    '#empty_option' => t('- rate type -'),
    '#prefix' => '<div class="container-inline row1">',
    '#required' => TRUE,
  );

  $form['price'] = array(
    '#type' => 'textfield',
    '#title' => t('Price'),
    '#field_prefix' => t('at') . '&nbsp;',
    '#field_suffix' => ' USD',
    '#size' => 10,
    '#required' => TRUE,
  );

  $date_fields = rooms_date_range_fields();

  $form['start_date'] = $date_fields['rooms_start_date'];
  $form['end_date'] = $date_fields['rooms_end_date'];

  $form['start_date']['#field_prefix'] = t('from') . '&nbsp;';
  $form['start_date']['#attributes'] = array('placeholder' => t('start date'));

  $form['end_date']['#field_prefix'] = t('to') . '&nbsp;';
  $form['end_date']['#attributes'] = array('placeholder' => t('end date'));
  $form['end_date']['#suffix'] .= '</div>';

  $day_options = array(
    '2' => t('Mon'),
    '3' => t('Tue'),
    '4' => t('Wed'),
    '5' => t('Thu'),
    '6' => t('Fri'),
    '7' => t('Sat'),
    '1' => t('Sun'),

  );
  $form['day_options'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Change only the following days:'),
    '#options' => $day_options,
    '#default_value' => array_keys($day_options),
    '#prefix' => '<div class="container-inline row2">',
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
    '#suffix' => '</div><br>',
  );

  return $form;
}

/**
 * Validate function for roomify_periodic_pricing_update_form form.
 */
function roomify_periodic_pricing_update_form_validate($form, &$form_state) {
  if (!empty($form_state['values']['price'])) {
    if (!is_numeric($form_state['values']['price'])) {
      form_set_error('price', t('%name: you must enter a numeric value.', array('%name' => t('Price'))));
    }
  }

  if (!empty($form_state['values']['start_date']) && !empty($form_state['values']['end_date'])) {
    $start_date = new DateTime($form_state['values']['start_date']);
    $end_date = new DateTime($form_state['values']['end_date']);

    if ($end_date < $start_date) {
      form_set_error('end_date', t('The End date must be greater or equal than the Start date.'));
    }
  }
}

/**
 * Submit callback for roomify_periodic_pricing_update_form form.
 */
function roomify_periodic_pricing_update_form_submit($form, &$form_state) {
  $values = $form_state['values'];

  $unit_id = $values['unit_id'];
  $rate_type = $values['rate_type'];
  $amount = $values['price'];
  $start_date = new DateTime($values['start_date']);
  $end_date = new DateTime($values['end_date']);
  $days = array_filter($form_state['values']['day_options']);

  if ($rate_type == 'nightly') {
    rooms_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, ROOMS_REPLACE, $days);
  }
  elseif ($rate_type == 'weekly' || $rate_type == 'monthly') {
    roomify_periodic_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, $rate_type, $days);
  }
}

/**
 * Builds a form when user can calculate price for a given date range and unit.
 */
function roomify_periodic_pricing_test_form($form, &$form_state, $unit_id) {
  $form['unit_id'] = array(
    '#type' => 'hidden',
    '#value' => $unit_id,
  );

  $form['price_tester'] = array(
    '#type' => 'fieldset',
    '#title' => t('Price tester'),
  );

  $form['price_tester'] += rooms_date_range_fields();
  // Unset a js setting that is not relevant for pricing.
  drupal_add_js(array('rooms' => array('roomsBookingStartDay' => 0)), 'setting');

  $form['price_tester']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Calculate price'),
    '#ajax' => array(
      'callback' => 'roomify_periodic_pricing_test_form_callback',
      'wrapper' => 'price-tester',
    ),
  );

  $form['price_tester']['price'] = array(
    '#prefix' => '<div id="price-tester">',
    '#markup' => '',
    '#suffix' => '</div>',
  );

  return $form;
}

/**
 * Submit callback for roomify_pricing_test_form form.
 */
function roomify_periodic_pricing_test_form_callback($form, &$form_state) {
  if (is_string($form_state['values']['rooms_start_date']) && is_string($form_state['values']['rooms_end_date'])) {
    $start_date = new DateTime($form_state['values']['rooms_start_date']);
    $end_date = new DateTime($form_state['values']['rooms_end_date']);

    $temp_end_date = clone($end_date);
    $temp_end_date->sub(new DateInterval('P1D'));

    $unit = rooms_unit_load($form_state['values']['unit_id']);

    $price_calendar = new UnitPricingCalendar($unit->unit_id);

    $price_log = $price_calendar->calculatePrice($start_date, $temp_end_date);
    $daily_price = $price_log['full_price'];

    $currency_setting = commerce_currency_load(commerce_default_currency());
    $currency_symbol = $currency_setting['symbol'];

    $weeks_months_days = roomify_periodic_pricing_calculate_weeks_months_days($start_date, $end_date);

    $current_apply = 1;

    // If "Monthly rate" is set and the current period is greater than or equal to 28 days.
    if ($weeks_months_days['months'] > 0 && $unit->monthly_discount > 0) {
      $current_apply = 3;
    }
    // If "Weekly rate" is set and the current period is greater than or equal to 7 days.
    elseif ($weeks_months_days['total_weeks'] > 0 && $unit->weekly_discount > 0) {
      $current_apply = 2;
    }

    $price = 0;

    $rc = new UnitMonthlyPricingCalendar($unit->unit_id);

    $monthly_price = round($rc->calculatePrice($start_date, $temp_end_date, $persons, $children, $children_ages) / 28, 2);

    $rc = new UnitWeeklyPricingCalendar($unit->unit_id);

    $weekly_price = round($rc->calculatePrice($start_date, $temp_end_date, $persons, $children, $children_ages) / 7, 2);

    if ($current_apply == 1) {
      $form['price_tester']['price']['#markup'] = '<div>' . t('Using Nightly rate: @currency_symbol@amount <- Applicable value given date range', array('@currency_symbol' => $currency_symbol, '@amount' => $daily_price)) . '</div>';
    }
    else {
      $form['price_tester']['price']['#markup'] = '<div>' . t('Using Nightly rate: @currency_symbol@amount', array('@currency_symbol' => $currency_symbol, '@amount' => $daily_price)) . '</div>';
    }
    if ($current_apply == 2) {
      $form['price_tester']['price']['#markup'] .= '<div>' . t('Using Weekly rate: @currency_symbol@amount <- Applicable value given date range', array('@currency_symbol' => $currency_symbol, '@amount' => $weekly_price)) . '</div>';
    }
    else {
      $form['price_tester']['price']['#markup'] .= '<div>' . t('Using Weekly rate: @currency_symbol@amount', array('@currency_symbol' => $currency_symbol, '@amount' => $weekly_price)) . '</div>';
    }
    if ($current_apply == 3) {
      $form['price_tester']['price']['#markup'] .= '<div>' . t('Using Monthly rate: @currency_symbol@amount <- Applicable value given date range', array('@currency_symbol' => $currency_symbol, '@amount' => $monthly_price)) . '</div>';
    }
    else {
      $form['price_tester']['price']['#markup'] .= '<div>' . t('Using Monthly rate: @currency_symbol@amount', array('@currency_symbol' => $currency_symbol, '@amount' => $monthly_price)) . '</div>';
    }
  }

  return $form['price_tester']['price'];
}

/**
 * Implements hook_form_FORM_ID_alter().
 */
function roomify_periodic_pricing_form_rooms_unit_edit_form_alter(&$form, &$form_state) {
  $unit = $form['#entity'];

  $form['weekly_monthly_discount'] = array(
    '#type' => 'fieldset',
    '#title' => t('Weekly/Monthly rate'),
    '#tree' => FALSE,
    '#weight' => -97,
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['weekly_monthly_discount']['weekly_discount'] = array(
    '#type' => 'textfield',
    '#title' => t('Weekly rate'),
    '#default_value' => isset($unit->weekly_discount) ? $unit->weekly_discount : '',
    '#size' => '5',
    '#field_suffix' => t('(> 7 days)'),
    '#description' => t('You can provide here the full rate that will be applied to the standard cost for bookings that exceed 7 days.'),
    '#maxlength' => 10,
  );

  $form['weekly_monthly_discount']['monthly_discount'] = array(
    '#type' => 'textfield',
    '#title' => t('Monthly rate'),
    '#default_value' => isset($unit->monthly_discount) ? $unit->monthly_discount : '',
    '#size' => '5',
    '#field_suffix' => t('(> 28 days)'),
    '#description' => t('You can provide here the full rate that will be applied to the standard cost for bookings that exceed 28 days.'),
    '#maxlength' => 10,
  );

  if (isset($unit->weekly_discount) && $unit->weekly_discount == '0.00') {
    $form['weekly_monthly_discount']['weekly_discount']['#default_value'] = '';
  }
  if (isset($unit->monthly_discount) && $unit->monthly_discount == '0.00') {
    $form['weekly_monthly_discount']['monthly_discount']['#default_value'] = '';
  }

  $form['#validate'][] = 'roomify_periodic_pricing_form_rooms_unit_edit_form_validate';

  $form['#attached']['css'][] = drupal_get_path('module', 'roomify_periofic_pricing') . '/css/roomify_periodic_pricing.css';
}

/**
 * Validate 'Weekly rate' and 'Monthly rate'.
 */
function roomify_periodic_pricing_form_rooms_unit_edit_form_validate(&$form, &$form_state) {
  if (empty($form_state['values']['weekly_discount'])) {
    $form_state['values']['weekly_discount'] = '0';
  }
  elseif (!empty($form_state['values']['weekly_discount'])) {
    if (!is_numeric($form_state['values']['weekly_discount'])) {
      form_set_error('weekly_discount', t('%name: you must enter a numeric value for the weekly rate.', array('%name' => t('Weekly rate'))));
    }
    elseif ($form_state['values']['weekly_discount'] < 0) {
      form_set_error('weekly_discount', t('%name: you must enter a valid value for the weekly rate.', array('%name' => t('Weekly rate'))));
    }
  }

  if (empty($form_state['values']['monthly_discount'])) {
    $form_state['values']['monthly_discount'] = '0';
  }
  elseif (!empty($form_state['values']['monthly_discount'])) {
    if (!is_numeric($form_state['values']['monthly_discount'])) {
      form_set_error('monthly_discount', t('%name: you must enter a numeric value for the monthly rate.', array('%name' => t('Monthly rate'))));
    }
    elseif ($form_state['values']['monthly_discount'] < 0) {
      form_set_error('weekly_discount', t('%name: you must enter a valid value for the monthly rate.', array('%name' => t('Monthly rate'))));
    }
  }
}

function roomify_periodic_pricing_bulk_pricing_management($year = '', $month = '', $type = 'all') {

  // Load FullCalendar Scheduler.
  rooms_library_loaded('fullcalendar-scheduler', 'minified');

  // Add css styles for one-month-calendar.
  drupal_add_css(drupal_get_path('module', 'rooms_availability') . '/css/fullcalendar.theme.css');

  // Inject settings in javascript that will be used to setup the three months
  // display.
  drupal_add_js(array('roomsCalendar' => array('currentMonth' => intval($month))), 'setting');
  drupal_add_js(array('roomsCalendar' => array('currentYear' => intval($year))), 'setting');
  drupal_add_js(array('roomsCalendar' => array('schedulerLicenseKey' => $schedulerlicensekey)), 'setting'); 

  // If year is not set then give it the current date.
  $year = ($year == '') ? date('Y', time()) : $year;
  $month = ($month == '') ? date('n', time()) : $month;
  $type = ($type == '') ? 'all' : $type;

  // It's not a valid unit type.
  if (rooms_unit_get_types($type) == FALSE) {
    $type = 'all';
  }

  // It's not a valid month or not valid year.
  $year_options = range(date('Y', time()) - 2, date('Y', time()) + 5);
  if ($month < 1 || $month > 12 || !in_array($year, $year_options)) {
    $year = date('Y', time());
    $month = date('n', time());
  }

  $efq = new EntityFieldQuery();
  $efq->entityCondition('entity_type', 'rooms_unit');
  $efq->addTag('rooms_pricing_access');
  if ($type != 'all') {
    $efq->entityCondition('bundle', $type, '=');
  }
  $efq->pager(20);
  $rooms_units = $efq->execute();

  $rooms_id = array();
  $rooms_name = array();
  $units = array();
  if ($rooms_units) {
    $units = array_values(entity_load('rooms_unit', array_keys($rooms_units['rooms_unit'])));

    $rooms_id = array();
    foreach ($units as $value) {
      $rooms_id[] = $value->unit_id;
      $rooms_name[] = $value->name;
    }
  }

  // Return the full render array.
  return array(
    drupal_get_form('rooms_filter_month_form', $month, $year),
    drupal_get_form('roomify_periodic_pricing_management_update_form', $month, $year, $type, $units),
    array(
      '#theme' => 'pager',
    ),
    '#attached' => array(
      'css' => array(
        drupal_get_path('module', 'rooms_pricing') . '/css/rooms_pricing.css',
        drupal_get_path('module', 'roomify_periodic_pricing') . '/css/roomify_periodic_pricing.css',
      ),
      'js' => array(
        drupal_get_path('module', 'roomify_periodic_pricing') . '/js/rooms_periodic_pricing_management.js',
        array(
          'data' => array(
            'roomsUnitManagement' => array(
              'roomsNumber' => count($rooms_id),
              'currentMonth' => $month,
              'currentYear' => $year,
              'roomsId' => $rooms_id,
              'roomsName' => $rooms_name,
            ),
          ),
          'type' => 'setting',
        ),
      ),
    ),
  );
}

/**
 * Pricing update form.
 */
function roomify_periodic_pricing_management_update_form($form, &$form_state, $month, $year, $type, $rooms_units) {
  $form['#attached']['css'][] = drupal_get_path('module', 'roomify_periodic_pricing') . '/css/roomify_periodic_pricing.css';

  $form['rooms_pricing_update'] = array(
    '#type' => 'fieldset',
    '#title' => t('Update Pricing'),
    '#description' => t('Apply a pricing adjustment in bulk to the units selected below for the specified date range.'),
    '#collapsible' => TRUE,
    '#collapsed' => TRUE,
  );

  $form['rooms_pricing_update']['curr_month'] = array(
    '#type' => 'hidden',
    '#value' => $month,
  );

  $form['rooms_pricing_update']['curr_year'] = array(
    '#type' => 'hidden',
    '#value' => $year,
  );

  $form['rooms_pricing_update']['curr_type'] = array(
    '#type' => 'hidden',
    '#value' => $type,
  );

  $form['rooms_pricing_update']['description'] = array(
    '#markup' => '<div>Pricing Rates can be changed from day to day to allow you to fine-tune your prices.</div><br><div>You always enter the full rate amount for the rate you are editing.<br>For example, if your weekly rate is $800 /week you will enter $800 for each night that rate applies.</div><br>',
  );

  $form['rooms_pricing_update']['rate_type'] = array(
    '#type' => 'select',
    '#title' => t('Rate type'),
    '#options' => array('nightly' => 'Nightly', 'weekly' => 'Weekly (7 nights)', 'monthly' => 'Monthly (28 nights)'),
    '#field_prefix' => t('Set') . '&nbsp;',
    '#empty_option' => t('- rate type -'),
    '#prefix' => '<div class="container-inline row1">',
    '#required' => TRUE,
  );

  $form['rooms_pricing_update']['price'] = array(
    '#type' => 'textfield',
    '#title' => t('Price'),
    '#field_prefix' => t('at') . '&nbsp;',
    '#field_suffix' => ' USD',
    '#size' => 10,
    '#required' => TRUE,
  );

  $date_fields = rooms_date_range_fields();

  $form['rooms_pricing_update']['start_date'] = $date_fields['rooms_start_date'];
  $form['rooms_pricing_update']['end_date'] = $date_fields['rooms_end_date'];

  $form['rooms_pricing_update']['start_date']['#field_prefix'] = t('from') . '&nbsp;';
  $form['rooms_pricing_update']['start_date']['#attributes'] = array('placeholder' => t('start date'));

  $form['rooms_pricing_update']['end_date']['#field_prefix'] = t('to') . '&nbsp;';
  $form['rooms_pricing_update']['end_date']['#attributes'] = array('placeholder' => t('end date'));
  $form['rooms_pricing_update']['end_date']['#suffix'] .= '</div>';

  $day_options = array(
    '1' => t('Sun'),
    '2' => t('Mon'),
    '3' => t('Tue'),
    '4' => t('Wed'),
    '5' => t('Thu'),
    '6' => t('Fri'),
    '7' => t('Sat'),
  );
  $form['rooms_pricing_update']['day_options'] = array(
    '#type' => 'checkboxes',
    '#title' => t('Change only the following days:'),
    '#options' => $day_options,
    '#default_value' => array_keys($day_options),
    '#prefix' => '<div class="container-inline row2">',
  );

  $form['rooms_pricing_update']['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Update'),
    '#suffix' => '</div>',
  );

  $form['rooms_data'] = array(
    '#prefix' => '<table class="rooms-month-manager">',
    '#type' => 'container',
    '#suffix' => '</tbody></table>',
  );

  if (count($rooms_units) > 0) {
    $date = new DateTime();
    $date->setDate($year, $month, '01');
    $form['rooms_data']['select-all'] = array(
      '#type' => 'select',
      '#prefix' => '<thead><tr><th class="unit-bulk-select">',
      '#options' => array(
        ROOMS_THIS_PAGE => t('All (this page)'),
        ROOMS_ALL_PAGES => t('All (all pages)'),
        ROOMS_NONE => t('None')),
      '#empty_option' => t('- Select -'),
      '#suffix' => '</th><th class="month-name"><div class="fc-header-title"><h2>' . format_date($date->getTimestamp(), 'custom', 'F Y') . '</h2></div></th></tr></thead><tbody>',
    );
  }

  foreach ($rooms_units as $key => $value) {
    $form['rooms_data']['rooms-' . $value->unit_id] = array(
      '#type' => 'checkbox',
      '#title' => $value->name,
      '#prefix' => '<tr><th class="unit-name">',
      '#suffix' => '</th><td class="unit-days"><div id="calendar' . $key . '"></div></td></tr>',
    );
  }

  return $form;
}

/**
 * Validate function for roomify_periodic_pricing_management_update_form form.
 */
function roomify_periodic_pricing_management_update_form_validate(&$form, &$form_state) {
  // Validate that a room is selected.
  _rooms_select_rooms_validation($form_state);
}

/**
 * Submit callback for roomify_periodic_pricing_management_update_form form.
 */
function roomify_periodic_pricing_management_update_form_submit(&$form, &$form_state) {
  $values = $form_state['values'];

  $rate_type = $values['rate_type'];
  $amount = $values['price'];
  $start_date = new DateTime($values['start_date']);
  $end_date = new DateTime($values['end_date']);
  $type = $form_state['values']['curr_type'];
  $days = array_filter($form_state['values']['day_options']);

  if ($form_state['values']['select-all'] == ROOMS_ALL_PAGES) {
    $query = db_select('rooms_units', 'n')->fields('n', array('unit_id', 'name'));
    if ($type != 'all') {
      $query->condition('type', $type, '=');
    }
    $rooms_units = $query->execute()->fetchAll();

    foreach ($rooms_units as $room) {
      $unit_id = $room->unit_id;

      if ($rate_type == 'nightly') {
        rooms_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, ROOMS_REPLACE, $days);
      }
      elseif ($rate_type == 'weekly' || $rate_type == 'monthly') {
        roomify_periodic_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, $rate_type, $days);
      }
    }
  }
  else {
    foreach ($form_state['values'] as $key => $value) {
      if (strpos($key, 'rooms-') === 0 && $value == '1') {
        $unit_id = str_replace('rooms-', '', $key);

        if ($rate_type == 'nightly') {
          rooms_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, ROOMS_REPLACE, $days);
        }
        elseif ($rate_type == 'weekly' || $rate_type == 'monthly') {
          roomify_periodic_pricing_update_calendar_event($unit_id, $amount, $start_date, $end_date, $rate_type, $days);
        }
      }
    }
  }
}
